#!/bin/bash

# Emplacement du fichier manifest à créer
MANI=/sdarinot/08_P3M_Maeva/manifest_selected.tsv

# Emplacement des séquences
SEQ_FILE=/sdarinot/08_P3M_Maeva/data/selected/

echo -e "sample-id\tforward-absolute-filepath\treverse-absolute-filepath" > "${MANI}"

for FOR in "${SEQ_FILE}"*R1.fastq.gz; do  ID=$(basename $FOR | cut -d . -f 5); REV=${FOR/_R1/_R2}; echo -e "${ID}\t${FOR}\t${REV}"; done >> "${MANI}"
