#!/usr/bin/env bash
#PBS -q omp
#PBS -l ncpus=2
#PBS -l mem=16gb
#PBS -l walltime=00:20:00

# Chargement de l'environnement Qiime
. /qiime/2022.11/env.sh

# pour le 16s faire: --p-exclude avec tax_to_exclude=Eukaryota (on veut garder les bactéries ET les archées)
# pour le 18s faire: --p-include avec tax_to_include=Eukaryota (on veut seulement les eukaryotes)

asv_table=/sdarinot/01_COMET/comet/01_Analysis_18s/02_Qiime_dbotu/dbotu_table.qza
asv_seq=/sdarinot/01_COMET/comet/01_Analysis_18s/02_Qiime_dbotu/dbotu_seqs.qza
asv_tax=/sdarinot/01_COMET/comet/01_Analysis_18s/03_Qiime_taxonomy/pr2_taxonomy.qza
tax_to_include="Eukaryota"
filtered_table=/sdarinot/01_COMET/comet/01_Analysis_18s/04_Qiime_filtering/pr2_filtered_tax_table.qza
filtered_seq=/sdarinot/01_COMET/comet/01_Analysis_18s/04_Qiime_filtering/pr2_filtered_tax_seq.qza
filtered_tableqzv=/sdarinot/01_COMET/comet/01_Analysis_18s/04_Qiime_filtering/pr2_filtered_tax_table.qzv
filtered_seqqzv=/sdarinot/01_COMET/comet/01_Analysis_18s/04_Qiime_filtering/pr2_filtered_tax_seq.qzv
metadata=/sdarinot/01_COMET/comet/01_Analysis_18s/sample_metadata
filtered_tax_output=/sdarinot/01_COMET/comet/01_Analysis_18s/04_Qiime_filtering/pr2_filtered_tax_output
asv_tax_tsv=/sdarinot/01_COMET/comet/01_Analysis_18s/03_Qiime_taxonomy/pr2_taxonomy_asv_final.tsv
final_filtered_table_biom=/sdarinot/01_COMET/comet/01_Analysis_18s/04_Qiime_filtering/pr2_filtered_table_final.biom
final_filtered_table_tsv=/sdarinot/01_COMET/comet/01_Analysis_18s/04_Qiime_filtering/pr2_filtered_table_final.tsv

qiime taxa filter-table \
 --i-table ${asv_table} \
 --i-taxonomy ${asv_tax} \
 --p-include ${tax_to_include} \
 --o-filtered-table ${filtered_table}

qiime taxa filter-seqs \
 --i-sequences ${asv_seq} \
 --i-taxonomy ${asv_tax} \
 --p-include ${tax_to_include} \
 --o-filtered-sequences ${filtered_seq}

#export table
qiime feature-table summarize \
 --i-table ${filtered_table} \
 --o-visualization ${filtered_tableqzv} \
 --m-sample-metadata-file ${metadata}

qiime tools export \
 --input-path ${filtered_tableqzv} \
 --output-path ${filtered_tax_output}

#export sequences
qiime feature-table tabulate-seqs \
 --i-data ${filtered_seq} \
 --o-visualization ${filtered_seqqzv}

qiime tools export \
 --input-path ${filtered_seqqzv} \
 --output-path ${filtered_tax_output}

#export table avec le metadata
qiime tools export \
 --input-path ${filtered_table} \
 --output-path ${filtered_tax_output}

biom add-metadata \
 -i ${filtered_tax_output}/feature-table.biom \
 --observation-metadata-fp ${asv_tax_tsv} \
 -o ${final_filtered_table_biom} \
 --sc-separated taxonomy

biom convert \
 -i ${final_filtered_table_biom} \
 -o ${final_filtered_table_tsv} \
 --to-tsv \
 --header-key taxonomy
